# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      PORT: 3000
      NODE_ENV: prod
      DB_NAME: postcodes
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 54321
      GEOLOCATION_SERVICE_URL: http://localhost:8080/postcodes/v1/postcodes
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      POSTCODESIO_HOST: https://api.postcodes.io

  postgres:
    image: postgres:10.4
    ports:
      - "54321:54321"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postcodes